functionsDirectory = "E:\\OST\\Webscrapper\\sistema_actplan\\sistema_actplan2\\project\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "E:\\OST\\Webscrapper\\sistema_actplan\\sistema_actplan2\\project\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "E:\\OST\\Webscrapper\\sistema_actplan\\sistema_actplan2\\project"
command = "npm run build"
functions = "E:\\OST\\Webscrapper\\sistema_actplan\\sistema_actplan2\\project\\netlify\\functions"

[build.environment]
SECRETS_SCAN_OMIT_KEYS = "VITE_EXTRACTION_API_URL,VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]