services:
  # Serviço de processamento de PDF
  pdf-processor:
    build:
      context: ./pdf-processor
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"  # Expõe a porta para acesso externo
    volumes:
      - ./pdf-processor:/app
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Nginx para proxy reverso e SSL
  nginx-proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-vps.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - pdf-processor

  # Certbot para SSL
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  pdf-cache:
