[tool.poetry]
name = "pdf-processor"
version = "0.1.0"
description = "API service for processing PDF documents using Docling"
authors = ["Your Name <you@example.com>"]
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
python-multipart = "^0.0.9"
pymupdf = "^1.23.26"
pandas = "^2.2.2"
pytesseract = "^0.3.10"
pdf2image = "^1.17.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
