[tool.poetry]
name = "pdf-processor"
version = "0.1.0"
description = "API service for processing PDF documents using Docling"
authors = ["Your Name <you@example.com>"] # Placeholder - update if needed
readme = "README.md" # Optional README for the service

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.111.0" # For building the API
uvicorn = {extras = ["standard"], version = "^0.29.0"} # ASGI server to run FastAPI
# docling = "^x.y.z" # Placeholder for Docling dependency - add later

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
